const RecipeData =[
  {
    id: "1",
    name: "Pizza Margherita",
    details: ["Flour dough ", "Basic marinara ", "Mozarella"],
    time: "30",
    src: './assets/margherita.jpeg',
    tools: ["cog"],
    ingredients: ["Dough", "Sauce", "Toppings"],
  },
  {
    id: "2",
    name: "Steak",
    details: ["BackEnd", "Data Science"],
    time: "300",
    src: 'https://www.seriouseats.com/thmb/sGmCdh11W1YtdHhHjosa2alkPJM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2015__05__Anova-Steak-Guide-Sous-Vide-Photos15-beauty-159b7038c56a4e7685b57f478ca3e4c8.jpg',
    tools: ["cog"],
    ingredients: ["Dough"],
  },
  {
    id: "3",
    name: "Spaghetti Carbonara",
    details: ["App Dev", "E-Commerce"],
    time: "50",
    src: 'https://static01.nyt.com/images/2021/02/14/dining/carbonara-horizontal/carbonara-horizontal-master768-v2.jpg?w=1280&q=75',
    tools: ["cog"],
    ingredients: ["Dough"],
  },
  {
    id: "4",
    name: "Butter Chicken",
    details: ["Databases"],
    time: "60",
    src: 'https://images.immediate.co.uk/production/volatile/sites/30/2021/02/butter-chicken-ac2ff98.jpg?quality=90&webp=true&resize=375,341',
    tools: ["cog"],
    ingredients: ["Dough"],
  },
  {
    id: "5",
    name: "Raclette Cheese",
    details: ["Databases"],
    time: "550",
    src: 'https://recipecontent.fooby.ch/22016_1-1_334-334@2x.jpg',
    tools: ["cog"],
    ingredients: ["Dough"],
  },
  {
    id: "6",
    name: "Salmon Filet",
    details: ["Game Dev", "Desktop Apps", "Mobile Apps"],
    time: "10",
    src: 'https://www.sunset.com/wp-content/uploads/4_3_horizontal_inbody_900x506/nancy-silverton-salmon-steaks-sun-61837-0420.jpg',
    tools: ["cog"],
    ingredients: ["Dough"],
  },
  {
    id: "7",
    name: "Chinese dumplings",
    details: ["Operating Systems", "VR", "Web Browsers"],
    time: "520",
    src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Xiaolongbao-breakfast.jpg/800px-Xiaolongbao-breakfast.jpg',
    tools: ["cog"],
    ingredients: ["Dough"],
  },
  {
    id: "8",
    name: "Fried Rice",
    details: ["System Administration", "GUI Development"],
    time: "230",
    src: 'https://therecipecritic.com/wp-content/uploads/2019/08/easy_fried_rice-4.png',
    tools: ["cog"],
    ingredients: ["Dough"],
  },
  {
    id: "9",
    name: "Truffle Cream Pasta",
    details: ["System Programming", "Audio Editing", "Big Data"],
    time: "380",
    src: 'https://www.en-vols.com/wp-content/uploads/afmm/2022/10/thumbnail_PATES-A-LA-TRUFFE-e1665745916891.png',
    tools: ["cog"],
    ingredients: ["Dough"],
  },
  {
    id: "10",
    name: "Käsespätzle",
    details: ["System Programming", "Audio Editing", "Big Data"],
    time: "380",
    src: 'https://www.feinschmecker.de/uploads/media/jalag-content-image/03/8413-ka%CC%88sespa%CC%88tzle.gif?v=1-0',
    tools: ["cog"],
    ingredients: ["Dough"],
  },
];

export default RecipeData;

