const RecipeData =[
  {
    id: "1",
    name: "Pizza Margherita",
    details: ["Flour dough ", "Basic marinara ", "Mozarella"],
    time: "30",
    src: 'https://images.prismic.io/eataly-us/ed3fcec7-7994-426d-a5e4-a24be5a95afd_pizza-recipe-main.jpg?auto=compress,format',
    tools: ["blender", "beaker", "stove", "trash-can", "microwave", "kettle", "grill", "pot-mix", "pot-steam", "chef-hat"],
    ingredients: ["Dough", "Sauce", "Toppings"],
  },
  {
    id: "2",
    name: "Steak",
    details: ["BackEnd", "Data Science"],
    time: "300",
    src: 'https://www.seriouseats.com/thmb/sGmCdh11W1YtdHhHjosa2alkPJM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2015__05__Anova-Steak-Guide-Sous-Vide-Photos15-beauty-159b7038c56a4e7685b57f478ca3e4c8.jpg',
    tools: ["grill", "chef-hat"],
    ingredients: ["Dough"],
  },
  {
    id: "3",
    name: "Spaghetti Carbonara",
    details: ["App Dev", "E-Commerce"],
    time: "50",
    src: 'https://static01.nyt.com/images/2021/02/14/dining/carbonara-horizontal/carbonara-horizontal-master768-v2.jpg?w=1280&q=75',
    tools: ["chef-hat"],
    ingredients: ["Dough"],
  },
  {
    id: "4",
    name: "Butter Chicken",
    details: ["Databases"],
    time: "60",
    src: 'https://images.immediate.co.uk/production/volatile/sites/30/2021/02/butter-chicken-ac2ff98.jpg?quality=90&webp=true&resize=375,341',
    tools: ["beaker", "chef-hat"],
    ingredients: ["Dough"],
  },
  {
    id: "5",
    name: "Raclette Cheese",
    details: ["Databases"],
    time: "550",
    src: 'https://recipecontent.fooby.ch/22016_1-1_334-334@2x.jpg',
    tools: ["kettle", "chef-hat"],
    ingredients: ["Dough"],
  },
  {
    id: "6",
    name: "Salmon Filet",
    details: ["Game Dev", "Desktop Apps", "Mobile Apps"],
    time: "10",
    src: 'https://www.sunset.com/wp-content/uploads/4_3_horizontal_inbody_900x506/nancy-silverton-salmon-steaks-sun-61837-0420.jpg',
    tools: ["pot-steam", "chef-hat"],
    ingredients: ["Dough"],
  },
  {
    id: "7",
    name: "Chinese dumplings",
    details: ["Operating Systems", "VR", "Web Browsers"],
    time: "520",
    src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Xiaolongbao-breakfast.jpg/800px-Xiaolongbao-breakfast.jpg',
    tools: ["pot-steam", "chef-hat"],
    ingredients: ["Dough"],
  },
  {
    id: "8",
    name: "Fried Rice",
    details: ["System Administration", "GUI Development"],
    time: "230",
    src: 'https://therecipecritic.com/wp-content/uploads/2019/08/easy_fried_rice-4.png',
    tools: ["pot-mix", "chef-hat"],
    ingredients: ["Dough"],
  },
  {
    id: "9",
    name: "Truffle Cream Pasta",
    details: ["System Programming", "Audio Editing", "Big Data"],
    time: "380",
    src: 'https://www.en-vols.com/wp-content/uploads/afmm/2022/10/thumbnail_PATES-A-LA-TRUFFE-e1665745916891.png',
    tools: ["blender", "chef-hat"],
    ingredients: ["Dough"],
  },
  {
    id: "10",
    name: "Käsespätzle",
    details: ["System Programming", "Audio Editing", "Big Data"],
    time: "380",
    src: 'https://www.feinschmecker.de/uploads/media/jalag-content-image/03/8413-ka%CC%88sespa%CC%88tzle.gif?v=1-0',
    tools: ["pot-mix", "chef-hat"],
    ingredients: ["Dough"],
  },
  {
    id: "11",
    name: "Pizza al funghi",
    details: ["Flour dough ", "Tomato sauce", "Mozarella"],
    time: "30",
    src: './assets/funghi.jpeg',
    tools: ["stove", "chef-hat"],
    ingredients: ["Dough", "Sauce", "Toppings"],
  },
  {
    id: "12",
    name: "Spaghetti Bolognese",
    details: ["Pasta", "Bolognese sauce", "Parmesan"],
    time: "10",
    src: './assets/Bolognese.jpeg',
    tools: ["pot-steam", "chef-hat"],
    ingredients: ["Pasta", "Sauce", "Cheese"],
  },
  {
    id: "13",
    name: "Burger",
    details: [""],
    time: "20",
    src: './assets/Burger.jpeg',
    tools: ["grill", "chef-hat"],
    ingredients: ["Burger bums", "Vegetables", "Sauce", "Greens"],
  },
  {
    id: "14",
    name: "Rosti",
    details: [""],
    time: "20",
    src: './assets/rosti.jpeg',
    tools: ["stove", "chef-hat"],
    ingredients: ["Vegetables", "Misc"],
  },
  {
    id: "15",
    name: "Chinese Chicken",
    details: [""],
    time: "60",
    src: './assets/General-Tso-Chicken.jpeg',
    tools: ["pot-steam", "chef-hat"],
    ingredients: ["Meat", "Misc", "Sauce", "Spices", "Rice"],
  },
  {
    id: "16",
    name: "Fish'n chips",
    details: [""],
    time: "60",
    src: './assets/fish_n_chips.jpeg',
    tools: ["trashcan", "chef-hat"],
    ingredients: ["Dough", "Alcohhol", "Fish", "Vegetables"],
  },
  {
    id: "17",
    name: "Peking pork",
    details: [""],
    time: "90",
    src: './assets/peking pork.jpeg',
    tools: ["pot-steam", "chef-hat"],
    ingredients: ["Meat", "Vegetables", "Spices", "Dough", "Sauce", "Alcohol"],
  },
  {
    id: "18",
    name: "Goulash",
    details: [""],
    time: "90",
    src: './assets/goulash.jpeg',
    tools: ["pot-steam", "chef-hat"],
    ingredients: ["Meat", "Vegetables", "Sauce", "Spices"],
  },
  {
    id: "19",
    name: "Crouton",
    details: [""],
    time: "10",
    src: './assets/Crouton.jpeg',
    tools: ["blender", "chef-hat"],
    ingredients: ["Spices", "Dough", "Misc"],
  },
  {
    id: "20",
    name: "Salmon rolls",
    details: [""],
    time: "15",
    src: './assets/Salmon roll.jpeg',
    tools: ["stove", "chef-hat"],
    ingredients: ["Fish", "Cheese", "Misc", "Greens"],
  },
  {
    id: "21",
    name: "Paella",
    details: [""],
    time: "80",
    src: './assets/Paella.jpeg',
    tools: ["pot-mix", "chef-hat"],
    ingredients: ["Meat", "Vegetables", "Spices"],
  },
  {
    id: "22",
    name: "Meatballs soup",
    details: [""],
    time: "90",
    src: './assets/Meatballs soup.jpeg',
    tools: ["pot-steam", "chef-hat"],
    ingredients: ["Meat", "Vegetables", "Pasta"],
  },
];

export default RecipeData;

